### PR TITLE
Produce a DOCTYPE for space invaders blocks.

### PR DESCRIPTION
**Pull request by jessica-norris**
Derp. This is a trivial fix.

Is there anything else I may have missed here, to make this valid html?

### CODE REVIEW

**Comment by timdawborn** [comment]
Is the HTML visible to the students? If not, adding
```html
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="msapplication-config" content="none">
```
to the `<head>` would also not hurt, but if it's visible, these are just going to add to the noise of HTML soup.

**Comment by jimmo** [comment]
I don't think any of the <meta> tags will make a difference any more, the doctype should be sufficient. https://stackoverflow.com/questions/6771258/what-does-meta-http-equiv-x-ua-compatible-content-ie-edge-do

**Comment by jessica-norris** [comment]
Yep, the HTML is visible to students in the generated code tab, and it's already fairly mysterious.

I would guess that Karsten needs to update the `index.html` that is read-only inside the non-blocky problem workspaces, too. These are hidden, however (and not affected by this blockly change, that's Karsten's problem to fix).

**Comment by jessica-norris** [comment]
@timdawborn , are you okay for this to merge as-is?

**Comment by timdawborn** [comment]
Sorry, I forgot about this PR. Merged.

**Pull request merged**
