### PR TITLE
Cookie clicker draft blocks

### PR DESCRIPTION
**Pull request by jessica-norris**
First cut at Blockly support for cookie clicker authoring:

screen shot 2018-03-16 at 6 15 51 pm

- Various HTML element blocks for `h1` `script` `img` `p` etc.
- Some basic attribute setter blocks to allow you set some attributes, plus to specifically set an event handler
- A couple of placeholder src url pickers (images to be determined from Kenni)

The text and design of these blocks is a draft for Kenni to start using with authoring and then give feedback.

There is a known issue with variable hoisting which is going to be fixed separately after these blocks are available for authoring, see groklearning/issues#361.

This PR fixed groklearning/issues#348. This PR contributes towards groklearning/issues#350 which will be closed with a separate PR (ayee these things are so complicated).

The function blocks from the image above are from blockly core which is in PR groklearning/blockly/pull/4.

Setting multiple reviewers in the hope of finding someone available -- the draft blocks milestone is due Monday. Thank you any and all.

### CODE REVIEW

**Comment by jimmo** [comment]
I had a go at this, seems to work and solves the variable definition issue -- https://github.com/groklearning/blockly-blocks/compare/cookie-clicker-blockly...cookie-clicker-blockly-html?expand=1

**Comment by jessica-norris** [comment]
@jimmo this is awesome. I will look at the PR on Monday morning (if not before) but it looks solid. Thank you!

**Comment by jessica-norris** [comment]
@jimmo Is there an accompanying PR for the groklearning/app repo to give support for this? I've made changes in `conf/assets.json` but I'm not getting the code generation working as expected.

**Comment by jessica-norris** [comment]
Okay, so a few things we need to fix here before merging:

1. We need a special HTML block for a url-encoded string (rather than a regular string which html escapes)
2. We need to fix the code generator for the 'set event handler block' so that it doesn't add single quotes to text strings.

screen shot 2018-03-19 at 9 35 50 am

3. The text inside the javascript might need to do something clever? In the following example the preview is broken:

screen shot 2018-03-19 at 9 50 08 am

However, the code gen looks okay (aside from the confused linting, perhaps):

screen shot 2018-03-19 at 9 51 41 am

**Comment by jessica-norris** [comment]
On further investigation, it looks like the babel plugin which does transpilation is the thing that does not like "</" inside a string. So I've merged in Jim's PR, this is now ready to review.

**Comment by jessica-norris** [comment]
This now also fixes groklearning/issues#361

**Pull request merged**
